# Generated by Django 3.0.4 on 2020-11-10 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0003_auto_20201107_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishingHouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('phone', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('city', models.TextField()),
                ('country', models.CharField(max_length=2)),
                ('works', models.NullBooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='p_house',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='p_library.PublishingHouse'),
        ),
    ]
