# Generated by Django 3.0.4 on 2020-11-10 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0005_auto_20201110_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishinghouse',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
