# Generated by Django 3.0.4 on 2020-11-10 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0006_auto_20201110_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishinghouse',
            name='foundation_date',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='publishinghouse',
            name='city',
            field=models.TextField(null=True),
        ),
    ]
