# Generated by Django 3.0.4 on 2020-11-11 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0007_auto_20201110_0957'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.TextField(verbose_name='Имя')),
                ('birth_year', models.SmallIntegerField(verbose_name='Год рождения')),
                ('phone', models.CharField(blank=True, max_length=16, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
            ],
        ),
        migrations.AlterField(
            model_name='author',
            name='birth_year',
            field=models.SmallIntegerField(verbose_name='Год рождения'),
        ),
        migrations.AlterField(
            model_name='author',
            name='country',
            field=models.CharField(max_length=2, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='author',
            name='full_name',
            field=models.TextField(verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='p_library.Author', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='book',
            name='copy_count',
            field=models.SmallIntegerField(default=1, verbose_name='Количество копий'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='book',
            name='p_house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='p_library.PublishingHouse', verbose_name='Издательство'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.FloatField(verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.TextField(verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='book',
            name='year_release',
            field=models.SmallIntegerField(verbose_name='Год публикации'),
        ),
        migrations.AlterField(
            model_name='publishinghouse',
            name='city',
            field=models.TextField(blank=True, null=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='publishinghouse',
            name='country',
            field=models.CharField(max_length=2, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='publishinghouse',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='publishinghouse',
            name='foundation_date',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Дата основания'),
        ),
        migrations.AlterField(
            model_name='publishinghouse',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='publishinghouse',
            name='phone',
            field=models.CharField(max_length=16, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='publishinghouse',
            name='works',
            field=models.NullBooleanField(verbose_name='Работает ли издательство'),
        ),
        migrations.CreateModel(
            name='WhenTook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when_took', models.DateField(verbose_name='Какого числа была взята книга')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p_library.Book', verbose_name='Книга')),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p_library.Friend', verbose_name='Друг')),
            ],
        ),
    ]
