# Generated by Django 3.0.4 on 2020-11-11 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0008_auto_20201111_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='friends',
            field=models.ManyToManyField(through='p_library.WhenTook', to='p_library.Friend'),
        ),
    ]
